apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-server-pv-volume
  labels:
    type: local
spec:
  # storageClassName: manual
  volumeMode: Filesystem
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/code-server/data"

